services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exam_notes
      MYSQL_USER: mysql
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_HOST: "%"          # allow host connections
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: